export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const GET_ALL_LISTINGS_SUCCESS = 'GET_ALL_LISTINGS_SUCCESS';
export const MESSAGE_SUCCESS = 'MESSAGE_SUCCESS';
export const ERROR_MESSAGE = 'ERROR_MESSAGE';
export const VERIFY_USER_SUCCESS = 'VERIFY_USER_SUCCESS';
export const UPLOAD_LISTING_SUCCESS = 'UPLOAD_LISTING_SUCCESS';
export const DELETE_LISTING_SUCCESS = 'DELETE_LISTING_SUCCESS';
